version: '3.8'

services:
  aptarserver:
    image: ghcr.io/marcodantonio/aptarserver:latest
    container_name: aptarserver
    volumes:
      - ${CONFIGDIR}/aptar/:/home/server
    ports:
      - 5000:5000                   # Porta da aprire
    environment:
      - YOLO_MODEL=Aptar-YoloV8.pt  # Modello da usare
      - FLASK_DEBUG=False           # Debug
      - FLASK_HOST=0.0.0.0          # Indirizzo IP del server Flask
      - FLASK_PORT=5000             # Porta del server Flask
      - SSL_CERT=cert.pem           # Nome del file del certificato SSL
      - SSL_KEY=key.pem             # Nome del file della chiave SSL
      - USER_ID=1001                # UID dell'utente desiderato
      - GROUP_ID=1001               # GID dell'utente desiderato